version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Генерирует кода из протофайла"
    cmds: 
      - protoc -I proto proto/sso/*.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative